server:
  port: 9090
spring:
  application:
    name: "UserAuthenticationService"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
routes:
  paths:
    users: "/api/v1/users"
    usersById: "/api/v1/users/{id}"
  login:
    login: "/api/v1/login"
adapters:
  r2dbc:
    host: "localhost"
    port: 5433
    database: "postgres"
    schema: "service"
    username: "postgres"
    password: "postgres"
logging:
  level:
    root: "INFO"
    co.com.tecnohalecatez: "TRACE"
