CREATE SCHEMA IF NOT EXISTS service AUTHORIZATION postgres;

COMMENT ON SCHEMA service IS 'service schema';

CREATE TABLE service.users (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   name VARCHAR(100) NOT NULL,
   surname VARCHAR(100) NOT NULL,
   birth_date DATE,
   address VARCHAR(200),
   phone VARCHAR(20),
   email VARCHAR(100) NOT NULL,
   base_salary DOUBLE PRECISION NOT NULL
);

CREATE TABLE service.roles (
   id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   name VARCHAR(100) NOT NULL,
   description VARCHAR(200)
);

INSERT INTO service.roles (name, description) VALUES
    ('GUEST', 'Invitado'),
    ('ADMIN', 'Administrador'),
    ('USER', 'Usuario'),
    ('SUPERVISOR', 'Supervisor'),
    ('ADVISER', 'Asesor');

ALTER TABLE service.users ADD COLUMN role_id INTEGER NOT NULL DEFAULT 1;
ALTER TABLE service.users ADD COLUMN password VARCHAR(100) NOT NULL DEFAULT '123456';

ALTER TABLE service.users ADD FOREIGN KEY (role_id) REFERENCES service.roles(id);
